name: FCIDataprovider
version: 1.0
author: TeamFCI

main: de.teamfci.dataprovider.dataprovider
commands:
  ple:
    description: Shows Plugin-Status
  fcid:
    description: Shows FCI-BaukastenID